### ISSUE TITLE
doesn't work with this error "live-code-runner: Internal Server Error: Executing user code in the kernel has failed."

### ISSUE THREAD

**Issue by Soonmok** [lablup/vscode-live-code-runner#12]
There is no syntax error but this error message poped up 
"live-code-runner: Internal Server Error: Executing user code in the kernel has failed."
and it works on local environment

**Comment by achimnol** [comment]
We have recently updated the VSCode extension, and I just checked up the keypair and session databases. Could you try once again and if the same issue persists?

**Comment by Soonmok** [comment]
it works now !! thanks!
